// Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate.
resolvers += "central-snapshots" at "https://central.sonatype.com/repository/maven-snapshots/"
forceUpdatePeriod := Some(scala.concurrent.duration.Duration.Zero)
addSbtPlugin("rocks.earlyeffect" % "sbt-zipx" % "0.18.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.7")
addSbtPlugin("rocks.earlyeffect" % "sbt-specular" % "0.14.1")
addSbtPlugin("rocks.earlyeffect" % "sbt-chekhov" % "0.1.1")
addSbtPlugin("rocks.earlyeffect" % "sbt-splice" % "0.3.2-42d1f350d30e-SNAPSHOT")
