// Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate.
addSbtPlugin("rocks.earlyeffect" % "sbt-zipx" % "0.8.1")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.7")
addSbtPlugin("rocks.earlyeffect" % "sbt-dynver-ci" % "0.2.2")
addSbtPlugin("rocks.earlyeffect" % "sbt-specular" % "0.14.1")
addSbtPlugin("rocks.earlyeffect" % "sbt-chekhov" % "0.0.4")
addSbtPlugin("rocks.earlyeffect" % "sbt-splice" % "0.1.0")
